acme_store_homepage:
    path:     /doctrine
    defaults: { _controller: AcmeStoreBundle:Default:create }

show:
    path: /doctrine/show/{id}
    defaults: { _controller: AcmeStoreBundle:Show:index }

relations:
    path: /doctrine/relations
    defaults: { _controller: AcmeStoreBundle:Relations:createProduct }

product:
    path: /product
    defaults: { _controller: AcmeStoreBundle:Product:add }

product_pushed:
    path: /product_pushed
    defaults: { _controller: AcmeStoreBundle:Product:index}
