Acme\TaskBundle\Entity\Task:
    properties:
        name:
            - NotBlank: ~
            - Type: \string

        description:
            - NotBlank: ~
            - Type: \string

        price:
            - NotBlank: ~
            - Type: \string
